version: '3'
services:
  node:
    container_name: 'pillar_dev'
    build:
      context: '../'
      dockerfile: '.devcontainer/docker/node/Dockerfile'
    image: 'pillar_dev_image'
    tty: true
    volumes:
      - '../:/workspace'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    command:
      /bin/bash -c "npm i && npm run dev"
    depends_on:
      - postgres
  postgres:
    container_name: 'pillar_dev_db'
    build:
      context: '../'
      dockerfile: '.devcontainer/docker/postgres/Dockerfile'
    restart: always
    volumes:
      - 'pillar_dev_db:/var/lib/postgresql/data'
      - '../database/init:/docker-entrypoint-initdb.d'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER:-postgres}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}'
      - 'POSTGRES_DB=${POSTGRES_DB:-pillar}'
      - 'POSTGRES_PORT=${POSTGRES_PORT:-5432}'
    ports:
      - '${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}'
volumes:
  pillar_dev_db: {}
